import * as types from './actionTypes.d';

export const FIELDS_BEFORE_FETCH: types.TYPE_FIELDS_BEFORE_FETCH = 'FIELDS_BEFORE_FETCH';
export const FIELDS_AFTER_FETCH: types.TYPE_FIELDS_AFTER_FETCH = 'FIELDS_AFTER_FETCH';
export const FIELDS_SET_META: types.TYPE_FIELDS_SET_META = 'FIELDS_SET_META';
export const FIELDS_ADD_SECURITY: types.TYPE_FIELDS_ADD_SECURITY = 'FIELDS_ADD_SECURITY';
export const FIELDS_REMOVE_SECURITY: types.TYPE_FIELDS_REMOVE_SECURITY = 'FIELDS_REMOVE_SECURITY';

export const LIST_INIT: types.TYPE_LIST_INIT = 'LIST_INIT';
export const LIST_BEFORE_FETCH: types.TYPE_LIST_BEFORE_FETCH = 'LIST_BEFORE_FETCH';
export const LIST_AFTER_FETCH: types.TYPE_LIST_AFTER_FETCH = 'LIST_AFTER_FETCH';
export const LIST_ITEM_UPDATE: types.TYPE_LIST_ITEM_UPDATE = 'LIST_ITEM_UPDATE';
export const LIST_DESTROY: types.TYPE_LIST_DESTROY = 'LIST_DESTROY';
export const LIST_TOGGLE_ITEM: types.TYPE_LIST_TOGGLE_ITEM = 'LIST_TOGGLE_ITEM';
export const LIST_TOGGLE_ALL: types.TYPE_LIST_TOGGLE_ALL = 'LIST_TOGGLE_ALL';

export const OPEN_MODAL: types.TYPE_OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL: types.TYPE_CLOSE_MODAL = 'CLOSE_MODAL';

export const NAVIGATION_INIT_ROUTES: types.TYPE_NAVIGATION_INIT_ROUTES = 'NAVIGATION_INIT_ROUTES';
export const NAVIGATION_SET_PARAMS: types.TYPE_NAVIGATION_SET_PARAMS = 'NAVIGATION_SET_PARAMS';

export const NOTIFICATIONS_SHOW: types.TYPE_NOTIFICATIONS_SHOW = 'NOTIFICATIONS_SHOW';
export const NOTIFICATIONS_CLOSING: types.TYPE_NOTIFICATIONS_CLOSING = 'NOTIFICATIONS_CLOSING';
export const NOTIFICATIONS_CLOSE: types.TYPE_NOTIFICATIONS_CLOSE = 'NOTIFICATIONS_CLOSE';

export const ROUTING_REGISTER: types.TYPE_ROUTING_REGISTER = 'ROUTING_REGISTER';