export type TYPE_FIELDS_BEFORE_FETCH = 'FIELDS_BEFORE_FETCH';
export type TYPE_FIELDS_AFTER_FETCH = 'FIELDS_AFTER_FETCH';
export type TYPE_FIELDS_SET_META = 'FIELDS_SET_META';
export type TYPE_FIELDS_ADD_SECURITY = 'FIELDS_ADD_SECURITY';
export type TYPE_FIELDS_REMOVE_SECURITY = 'FIELDS_REMOVE_SECURITY';

export type TYPE_LIST_INIT = 'LIST_INIT';
export type TYPE_LIST_BEFORE_FETCH = 'LIST_BEFORE_FETCH';
export type TYPE_LIST_AFTER_FETCH = 'LIST_AFTER_FETCH';
export type TYPE_LIST_ITEM_UPDATE = 'LIST_ITEM_UPDATE';
export type TYPE_LIST_DESTROY = 'LIST_DESTROY';
export type TYPE_LIST_TOGGLE_ITEM = 'LIST_TOGGLE_ITEM';
export type TYPE_LIST_TOGGLE_ALL = 'LIST_TOGGLE_ALL';

export type TYPE_OPEN_MODAL = 'OPEN_MODAL';
export type TYPE_CLOSE_MODAL = 'CLOSE_MODAL';

export type TYPE_NAVIGATION_INIT_ROUTES = 'NAVIGATION_INIT_ROUTES';
export type TYPE_NAVIGATION_SET_PARAMS = 'NAVIGATION_SET_PARAMS';

export type TYPE_NOTIFICATIONS_SHOW = 'NOTIFICATIONS_SHOW';
export type TYPE_NOTIFICATIONS_CLOSING = 'NOTIFICATIONS_CLOSING';
export type TYPE_NOTIFICATIONS_CLOSE = 'NOTIFICATIONS_CLOSE';

export type TYPE_ROUTING_REGISTER = 'ROUTING_REGISTER';
